### ISSUE TITLE
cannot find hid_rip.h

### ISSUE THREAD

**Issue by xrayer** [fruit-bat/pico-zxspectrum#10]
Hi, I'm trying to compile the current sources with tinyusb and libdvi but I got error missing hid_rip.h referenced by hid_host_joy.h of pico-emu-utils - where can I get this file?

**Comment by fruit-bat** [comment]
I think you are using the wrong version of TinyUSB. Have you replaced TinyUSB in the Pico SDK as per the first couple of paragraphs in the build instructions? If you have, check you don't have multiple copies in your build path.

**Comment by xrayer** [comment]
I read about this in the readme but git failed to clone the repo for me:

git clone git@github.com:fruit-bat/tinyusb.git
Cloning into 'tinyusb'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

So I downloaded the zip package from this page but file is missing there...

**Comment by fruit-bat** [comment]
Try cloning using https....


export PICO_SDK_PATH=~/pipico/pico-sdk
cd $PICO_SDK_PATH/lib/
mv tinyusb tinyusb.orig
git clone https://github.com/fruit-bat/tinyusb.git
cd tinyusb
git checkout hid_micro_parser

**Comment by fruit-bat** [comment]
...or download the zip for the hid_micro_parser branch

**Comment by xrayer** [comment]
Thanks for the hint, https works. I got it compiled, so closing now :)
