### ISSUE TITLE
Quick Save Function ZxSpectrumPicomputerVgaAukBob

### ISSUE THREAD

**Issue by digitalmexer** [fruit-bat/pico-zxspectrum#109]
Is it possible to add the quick save function with SHIFT + MENU in the firmware of "VgaAuKBob"? 
Some snapshots from PC emulators do not work properly. 
If you load a .tap file into the PICOZX and create a snapshot yourself, it always works. 
So it would be a very useful addition.

**Comment by fruit-bat** [comment]
Yup, I'll take a look at this when I get a mo.

**Comment by fruit-bat** [comment]
This should already be working in the latest firmware.  Let me know if it's not working properly.

**Comment by digitalmexer** [comment]
Quicksave works perfectly! 
I apologize, I used the old firmware for the test - it was my mistake.
Thank you very much for your help.
