### ISSUE TITLE
Are these implementations cycle-accurate?

### ISSUE THREAD

**Issue by Ev1lT3rm1nal** [fruit-bat/pico-zxspectrum#113]
AFAIK this replicates exactly the process made by a real spectrum, and I'd like to know if it is cycle-accurate

**Comment by fruit-bat** [comment]
Short answer is no... but in places it's not bad. It can read audio signals real time. The USB is handled on the same core as the emulator which causes glitches that are subsequently corrected for. The ay audio is split in half so some of it runs with the cpu but the rest is clocked at a constant rate so pitch does not alter with cpu speed. And so on.
