### ISSUE TITLE
Could be used USB joystick/gamepad in the emulator menu? 

### ISSUE THREAD

**Issue by DPRCZ** [fruit-bat/pico-zxspectrum#123]
USB joystick/gamepad has got usually four direction buttons and four other for fire. As far I know the zx spectrum joystick had only one fire button. Could be used some of the others fire buttons for enter to menu? And moreover, could be used the USB joystick/gamepad for movement in emulator menu then?

**Comment by fruit-bat** [comment]
Possibly, I'll have a look at how the code is set up. It will need some translation from joystick state changes to HID keyboard events, which isn't there at the moment.

**Comment by fruit-bat** [comment]
I've pushed some changes, which should work now along with configuration in the menus.

Please, let me know if you find anything that needs tidying up.  I think ZxSpectrumHidMouseJoystick.* can be removed but have left them there for now as reference, in case my merging of mouse and joystick isn't quite correct.

**Comment by DPRCZ** [comment]
Something missing in git "tinyusb?":
hid_app.c:(.text.tuh_hid_mount_cb+0x11c): undefined reference to `process_mouse_mount'
/usr/lib/gcc/arm-none-eabi/13.2.1/../../../arm-none-eabi/bin/ld: hid_app.c:(.text.tuh_hid_mount_cb+0x202): undefined reference to `process_mouse_mount'

**Comment by fruit-bat** [comment]
I'll have a look... what were you trying to build when you got that message?

**Comment by DPRCZ** [comment]
I did "git pull mousejoy" and than I tried to rebuild pico-zxspectrum project.

**Comment by fruit-bat** [comment]
you need to pull pico-emu-utils and tinyusb

**Comment by fruit-bat** [comment]
The examples are broken in TinyUSB at the moment - I'll fix them bit it's not looking simple at the mo.

**Comment by DPRCZ** [comment]
Yep, as I already said. Nesu zadne vorezavatko.

**Comment by fruit-bat** [comment]
Are you on the feature/mousejoy branch in pico-zxspectrum  ?

If not:

  git checkout feature/mouejoy

**Comment by fruit-bat** [comment]
I've merged the mousejoy branch back to main now. So you should be fine just building from there. If you got round to changing to the feature/mousejoy branch you should switch back to main (git checkout main)

You will need to pull:
* pico-emu-utils
* tinyusb
* pico-zxspectrum

**Comment by DPRCZ** [comment]
OK,  pico-zxspectrum is compiled. There is only one  issue: pico-zxspectrum/tree/main/src/picovga/main.cpp

static ZxSpectrum zxSpectrum(
  &keyboard1, 
  0, 
  &joystick,
  &mouse,
  0
);

Last 0 in constructor.

**Comment by fruit-bat** [comment]
Ah, thanks for that. Should be fixed now.

**Comment by DPRCZ** [comment]
What is new in this version? I thought that this version supports the USB joystick in setup menu (for movement and setting), but I probably wrong.

**Comment by fruit-bat** [comment]
A feature javavi has been helping with. It allows a USB mouse to be used as a joystick, with settings in the menu.

**Comment by DPRCZ** [comment]
Done.
