### ISSUE TITLE
50Hz refresh rate over HDMI

### ISSUE THREAD

**Issue by xelapo** [fruit-bat/pico-zxspectrum#128]
It's possible to implement a 50Hz refresh rate video output, the native format of the ZX Spectrum? Or should this issue be addressed to Wren, the author of PicoDVI? Congratulations and thank you for your work!

**Comment by fruit-bat** [comment]
It's fine to ask here... I think it's possible to do a 50Hz version but it would be a different resolution. 720x576 or similar, which means the encoder for the scanlines will need to change; not necessarily a bad thing but it's not just a case of changing a 60 to 50 in the code. I'll have a mess around with it when I get chance.

**Comment by fruit-bat** [comment]
50Hz mode now available for most hardware :-)
