### ISSUE TITLE
After "Switch to scanline VGA" stopped my board working

### ISSUE THREAD

**Issue by DPRCZ** [fruit-bat/pico-zxspectrum#167]
I'm using  build "ZxSpectrumPicomputerVgaAukBob_640x480x60Hz" . I've update git "https://github.com/fruit-bat/pico-extras".

I'm still use SDK 1.0 could be issue ??? 

Afer build firmware and download to RP2040 VGA doesn't start work - monitor is black  and  buzzer make a noise like button autorepat.

**Comment by fruit-bat** [comment]
You might need the latest sdk... but try completely clearing your build folder and running cmake again.  Make sure you have my version of pico extras.

**Comment by DPRCZ** [comment]
OK, I'll test your .UF2 file to ensure that problem is on my setup.  And I let you know the result.

**Comment by DPRCZ** [comment]
With your "ZxSpectrumPicomputerVgaAukBob_640x480x60Hz" is VGA working. Issue is on my PC . Letters  are not white but light blue now on Menu?

**Comment by fruit-bat** [comment]
> With your "ZxSpectrumPicomputerVgaAukBob_640x480x60Hz" is VGA working. Issue is on my PC . Letters are not white but light blue now on Menu?

Yup, VGA is working but the menu has gone a rather nice blue colour... don't know why. I will have a look.

**Comment by fruit-bat** [comment]
I've updated pico-dvi-menu to better handle the difference VGA encodings. Also, the builds can define the menu colour with symbol, e.g.

  PICO_MENU_FOREGROUND_COLOR=COLOR_BRIGHT_GREEN

Now defaulting to bright-white on black.

**Comment by DPRCZ** [comment]
My own compilation works  again. I've refreshed all from scratch from github.

**Comment by DPRCZ** [comment]
Fixed.
