### ISSUE TITLE
RP2350 files on RP2040 folder ??

### ISSUE THREAD

**Issue by Magnetrix** [fruit-bat/pico-zxspectrum#181]
RP2350 files on RP2040 folder ?? Thanks

**Comment by fruit-bat** [comment]
Not sure I understand.  Have I made a mistake somewhere?

**Comment by DPRCZ** [comment]
It is a message from commit line  :-(

**Comment by fruit-bat** [comment]
The uf2-rp2040 folder is for the rp2040 builds

**Comment by Magnetrix** [comment]
Thanks for the explanation
