### ISSUE TITLE
README.md reports USB host issue that should be fixed now

### ISSUE THREAD

**Issue by rppicomidi** [fruit-bat/pico-zxspectrum#3]
### The README.md file says:
USB host mode seems to work very reliably unless the keyboard is removed and reconnected, which causes the Pico to 'panic'.

This allows usb reconnect:
https://github.com/hathach/tinyusb/pull/1193/files

### The issue should be fixed with the latest tinyusb
The pull request was integrated and then refined.
@fruit-bat it may be worth retesting with the latest tinyusb build

**Comment by fruit-bat** [comment]
Thanks for the heads-up. I will have a look at what version the sdk is pinned at and at the least update the advice. Cheers!
