### ISSUE TITLE
cant get sound

### ISSUE THREAD

**Issue by mikrohouse** [fruit-bat/pico-zxspectrum#35]
hello i build your pi pico zx spectrum. every thing works perfectly except i cant get any sound,. i am using  retroVGA configuration. And i tried to get sound from all the pin combinations you have mentioned. any suggestions ??

**Comment by fruit-bat** [comment]
Try GP9

When I started this project I only expected to make one configuration... And now there are lots! I will raise a separate issue around clearly documenting the pins for each target.

**Comment by mikrohouse** [comment]
Thank you very much for the prompt reply
Achala

**Comment by fruit-bat** [comment]
You are welcome, have fun!
