### ISSUE TITLE
Where I can find the USB pins?

### ISSUE THREAD

**Issue by Chandler-Kluser** [fruit-bat/pico-zxspectrum#75]
Hello, I am assembling the Breadboard Version of pico-zxspectrum and I saw it is compatible with USB and PS2 keyboards.

I do not have any PS2 keyboards with me, but I looked for the D+ and D- pins to connect to my USB keyboard at pinout figure but I did not find any dedicated pin.

Could someone help me finding that? Thanks in advance!

**Comment by fruit-bat** [comment]
You can use an OTG adapter like this 
https://www.amazon.co.uk/CentBest-Splitter-Enhancer-Charging-Converter/dp/B072Z9QHYR/

Some have a built in hub, which I will post an example link if I can find one.

Or, if you are good at soldering, there are a couple of small pads on the back of the Pi Pico near the USB connector. If you add your own host connector, only use either the Pi Pico usb connector or yours, not both at the same time.

**Comment by Chandler-Kluser** [comment]
Thanks, I will try that :)

**Comment by Chandler-Kluser** [comment]
I have made a small prototype with and HDMI PMOD Adapter + TF Adapter + USB Type A Connector:

![01](https://github.com/fruit-bat/pico-zxspectrum/assets/29960960/6e346161-f8b8-4282-93ba-ab6940b7e255)
![02](https://github.com/fruit-bat/pico-zxspectrum/assets/29960960/4e24dce6-5b3f-4492-8ae1-7f3f590b8288)

Then I connected:

| USB CONNECTOR | RPI PICO |
|:-------------:|:--------:|
|     VBUS      |   VBUS   |
|      D+       |   TP3    |
|      D-       |   TP2    |
|     GND       |   GND    |

as @ArnoldUK mentioned. The HDMI pins were connected too.

The Board gave video output, as expected:

![Video Output](https://github.com/fruit-bat/pico-zxspectrum/assets/29960960/74acf590-04f2-419f-ae90-f474315a8ac2)

But when I attached my USB keyboard, it did not work...

![USB Type A keyboard](https://github.com/fruit-bat/pico-zxspectrum/assets/29960960/52489dd1-2eaf-417d-bba2-9f987134c885)

I also switched the D+ and D- just in case of I exchanged the pins by myself for accident, but it did not work either...

Are you sure the breadboard version does really support USB keyboards? Thanks in advance for your support!

**Comment by ArnoldUK** [comment]
If you are using your own USB OTG wiring to the D+ and D- pads then you cannot use the micro-usb socket as the D+ and D- in the micro-usb socket conflict. You should remove that micro-usb cable labeled USLION and power the pi directly with 5V to VSYS.

**Comment by Chandler-Kluser** [comment]
Thanks a lot!!

Wiring 5V power at VBUS and GND worked flawlessly!!!

I thought that connecting a Power Supply at OTG connector would not face issues but you are right. Thanks a lot!!

**Comment by ArnoldUK** [comment]
Yeah, glad to hear that worked. Like a said, some power adapters pull those data line low, others leave them floating.
