### ISSUE TITLE
error: 'CFG_TUH_ENDPOINT_MAX' undeclared here

### ISSUE THREAD

**Issue by shaeon** [fruit-bat/pico-zxspectrum#8]
Hello Again, 

I'm using your pre-built binary, and its work on my new pcb. I got sound, video, keyboard, all less sd-card access because i havent sd-card detect line. 

When i'm trying compile (in the past I got it) now i'm getting next error:
/pipico/PicoDVI/software/apps/pico-emu-utils/src/hid_host_info.c:26:38: error: 'CFG_TUH_ENDPOINT_MAX' undeclared here (not in a function)

![imagen](https://user-images.githubusercontent.com/10370710/163167844-a59f185d-22ac-4614-b9e8-ac96b1c5daa2.png)

whats i'm doing wrong?

Best Regards,
Shaeon.

**Comment by shaeon** [comment]
I got compile addin in file pico-emu-utils/src/hid_host_info.c
after the line #include "hid_host_info.h" next:
`#define` CFG_TUH_ENDPOINT_MAX 16`

**Comment by fruit-bat** [comment]
README has been updated. Let me know how you get on :-)

**Comment by shaeon** [comment]
Its working on!

Here its my notes about compile, maybe you can change git clone git@ because i cant get it by git clone https:// (and other slash after):

`cd ~

mkdir pipico
cd pipico
git clone https://github.com/raspberrypi/pico-sdk

export PICO_SDK_PATH=~/pipico/pico-sdk
cd $PICO_SDK_PATH/lib/
mv tinyusb tinyusb.orig
git clone https://github.com/fruit-bat/tinyusb.git
cd tinyusb
git checkout hid_micro_parser

cd ~/pipico/
git clone https://github.com/Wren6991/PicoDVI

cd PicoDVI/software/apps
git clone https://github.com/fruit-bat/pico-zxspectrum.git zxspectrum
git clone https://github.com/fruit-bat/no-OS-FatFS-SD-SPI-RPi-Pico.git
git clone https://github.com/fruit-bat/pico-dvi-menu
git clone https://github.com/fruit-bat/pico-emu-utils

Change in file "zxspectrum/src/hw_config.c" next line:
.card_detected_true = 1 
with
.card_detected_true = -1

Add to CMakeLists.txt file next lines (others can comment out with #):
add_subdirectory(pico-dvi-menu)
add_subdirectory(pico-emu-utils)
add_subdirectory(zxspectrum)
add_subdirectory(no-OS-FatFS-SD-SPI-RPi-Pico/FatFs_SPI)

cmake -DPICO_COPY_TO_RAM=0 ..
make clean
make -j4 ZxSpectrum

cp apps/zxspectrum/ZxSpectrum.uf2 /media/pi/RPI-RP2/`

I used a recolocator pcb in the atlas proyect:
https://github.com/theexperimentgroup/Atlas-FPGA

I change fpga for pi pipico as main bus. I'll publish scheme next monday at work for my pipico "recolocator" 

![photo1649839027](https://user-images.githubusercontent.com/10370710/163484040-b8c3d0af-5349-4814-b317-6ddaafd020e7.jpeg)

![photo1649845885](https://user-images.githubusercontent.com/10370710/163484059-d1007ed3-0bb1-4dd7-b768-54e01b1aa010.jpeg)

Thanks for your work, share, and fast fixing! :)

**Comment by shaeon** [comment]
I forgot tell you, you can use my notes if think can help more people, its free / open, you can do all you want with them :)

**Comment by fruit-bat** [comment]
Thanks for the pics and info 🙂
At some point I will add build notes with https: as an alternative to git@
