### ISSUE TITLE
Kempston Joystick

### ISSUE THREAD

**Issue by digitalmexer** [fruit-bat/pico-zxspectrum#82]

**Comment by digitalmexer** [comment]
I use the ingenious emulator PICOZX from Bobritius. Everything works very well but there is a problem with the Kempston interface:
When loading programs with the load function for TZX files, the joystick works fine with a snapshot not. The USB joystick always works.
Unfortunately I'm not a programmer so I can't find any hints about the bug in the sources.

**Comment by ArnoldUK** [comment]
I don't think the snapshots save the emulator joystick settings. reconfigure the joystick after loading the snapshot.
