### ISSUE TITLE
It doesn't save Volume level - I have to set it to max every single time I turn on my PICOZX

### ISSUE THREAD

**Issue by adamenkov** [fruit-bat/pico-zxspectrum#91]

**Comment by ArnoldUK** [comment]
I think this is more a feature request than an bug issue. Maybe a global settings file stored on the sd-card would be a good feature to request.

**Comment by fruit-bat** [comment]
https://kevinboone.me/picoflash.html?i=1

**Comment by fruit-bat** [comment]
I thought these settings would be good to write to the flash memory... until I tried to do it. 
Might read/write a file to the sd card as suggested.

See https://github.com/fruit-bat/pico-zxspectrum/tree/feature/persistent-settings
